name: CI

on:
  push:
    paths:
      - '**.kts'
      - '.github/**'
      - 'docs/**'
      - 'src/**'
    branches-ignore:      
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Build core JAR
        run: ./gradlew coreJar --no-daemon --stacktrace --console=plain     

      - name: Run tests
        run: ./gradlew test --no-daemon --info --console=plain --rerun-tasks

      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport
      
      - name: Upload code coverage report
        uses: codecov/codecov-action@v1     
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
