name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build core project
        run: './gradlew core:build --no-daemon --stacktrace --console=plain --rerun-tasks'

      - name: Build core JAR
        run: './gradlew core:coreJar --no-daemon --stacktrace --console=plain --rerun-tasks'

      - name: Build lib project
        run: './gradlew lib:build --no-daemon --stacktrace --console=plain --rerun-tasks'

      - name: Publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/LGP-core.jar
          asset_name: LGP-core-$tag.jar
          tag: ${{ github.ref }}
          overwrite: true