name: Release

on:
  push:
    paths:
      - '**.kts'
      - '.github/**'
      - 'docs/**'
      - 'core/**'
      - 'lib/**'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build projects
        run: './gradlew build --no-daemon --stacktrace --console=plain --rerun-tasks'

      - name: Build core JAR
        run: './gradlew core:coreJar --no-daemon --stacktrace --console=plain --rerun-tasks'

      - name: Generate code coverage report
        run: './gradlew core:jacocoTestReport --no-daemon'
      
      - name: Upload code coverage report
        uses: codecov/codecov-action@v1     
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate API documentation
        if: ${{github.event_name == 'push'}}
        # Note the `--no-daemon` is important here to avoid memory leaks.
        # See https://github.com/Kotlin/dokka/issues/1405 for more details
        run: './gradlew dokkaHtml --no-daemon && ./gradlew dokkaJavaDoc --no-daemon'

      - name: Publish API documentation
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: docs
          folder: docs/api/
          target-folder: docs/api/